package cz.maxtechnik.mtc;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

import static net.minecraft.world.level.block.Blocks.*;
@SuppressWarnings("unused")
public class MTCModBlocks{
	public static final DeferredRegister.Blocks REGISTRY=DeferredRegister.createBlocks(MTCMod.MODID);
	static BlockBehaviour.Properties c_cobblestone_props=BlockBehaviour.Properties.ofFullCopy(COBBLESTONE);
	public static final DeferredBlock<Block> C1_COBBLESTONE=REGISTRY.registerSimpleBlock("c1_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C2_COBBLESTONE=REGISTRY.registerSimpleBlock("c2_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C3_COBBLESTONE=REGISTRY.registerSimpleBlock("c3_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C4_COBBLESTONE=REGISTRY.registerSimpleBlock("c4_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C5_COBBLESTONE=REGISTRY.registerSimpleBlock("c5_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C6_COBBLESTONE=REGISTRY.registerSimpleBlock("c6_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C7_COBBLESTONE=REGISTRY.registerSimpleBlock("c7_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C8_COBBLESTONE=REGISTRY.registerSimpleBlock("c8_cobblestone",c_cobblestone_props);
	public static final DeferredBlock<Block> C9_COBBLESTONE=REGISTRY.registerSimpleBlock("c9_cobblestone",c_cobblestone_props);
	static BlockBehaviour.Properties c_dirt_props=BlockBehaviour.Properties.ofFullCopy(DIRT);
	public static final DeferredBlock<Block> C1_DIRT=REGISTRY.registerSimpleBlock("c1_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C2_DIRT=REGISTRY.registerSimpleBlock("c2_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C3_DIRT=REGISTRY.registerSimpleBlock("c3_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C4_DIRT=REGISTRY.registerSimpleBlock("c4_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C5_DIRT=REGISTRY.registerSimpleBlock("c5_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C6_DIRT=REGISTRY.registerSimpleBlock("c6_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C7_DIRT=REGISTRY.registerSimpleBlock("c7_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C8_DIRT=REGISTRY.registerSimpleBlock("c8_dirt",c_dirt_props);
	public static final DeferredBlock<Block> C9_DIRT=REGISTRY.registerSimpleBlock("c9_dirt",c_dirt_props);
	static BlockBehaviour.Properties c_gravel_props=BlockBehaviour.Properties.ofFullCopy(GRAVEL);
	public static final DeferredBlock<Block> C1_GRAVEL=REGISTRY.registerSimpleBlock("c1_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C2_GRAVEL=REGISTRY.registerSimpleBlock("c2_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C3_GRAVEL=REGISTRY.registerSimpleBlock("c3_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C4_GRAVEL=REGISTRY.registerSimpleBlock("c4_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C5_GRAVEL=REGISTRY.registerSimpleBlock("c5_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C6_GRAVEL=REGISTRY.registerSimpleBlock("c6_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C7_GRAVEL=REGISTRY.registerSimpleBlock("c7_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C8_GRAVEL=REGISTRY.registerSimpleBlock("c8_gravel",c_gravel_props);
	public static final DeferredBlock<Block> C9_GRAVEL=REGISTRY.registerSimpleBlock("c9_gravel",c_gravel_props);
	static Supplier<? extends Block> c_deepslate=()->new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(DEEPSLATE));
	public static final DeferredBlock<Block> C1_DEEPSLATE=REGISTRY.register("c1_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C2_DEEPSLATE=REGISTRY.register("c2_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C3_DEEPSLATE=REGISTRY.register("c3_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C4_DEEPSLATE=REGISTRY.register("c4_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C5_DEEPSLATE=REGISTRY.register("c5_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C6_DEEPSLATE=REGISTRY.register("c6_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C7_DEEPSLATE=REGISTRY.register("c7_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C8_DEEPSLATE=REGISTRY.register("c8_deepslate",c_deepslate);
	public static final DeferredBlock<Block> C9_DEEPSLATE=REGISTRY.register("c9_deepslate",c_deepslate);
	static BlockBehaviour.Properties c_cobbled_deepslate_props=BlockBehaviour.Properties.ofFullCopy(COBBLED_DEEPSLATE);
	public static final DeferredBlock<Block> C1_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c1_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C2_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c2_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C3_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c3_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C4_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c4_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C5_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c5_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C6_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c6_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C7_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c7_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C8_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c8_cobbled_deepslate",c_cobbled_deepslate_props);
	public static final DeferredBlock<Block> C9_COBBLED_DEEPSLATE=REGISTRY.registerSimpleBlock("c9_cobbled_deepslate",c_cobbled_deepslate_props);
	static BlockBehaviour.Properties c_diorite_props=BlockBehaviour.Properties.ofFullCopy(DIORITE);
	public static final DeferredBlock<Block> C1_DIORITE=REGISTRY.registerSimpleBlock("c1_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C2_DIORITE=REGISTRY.registerSimpleBlock("c2_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C3_DIORITE=REGISTRY.registerSimpleBlock("c3_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C4_DIORITE=REGISTRY.registerSimpleBlock("c4_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C5_DIORITE=REGISTRY.registerSimpleBlock("c5_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C6_DIORITE=REGISTRY.registerSimpleBlock("c6_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C7_DIORITE=REGISTRY.registerSimpleBlock("c7_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C8_DIORITE=REGISTRY.registerSimpleBlock("c8_diorite",c_diorite_props);
	public static final DeferredBlock<Block> C9_DIORITE=REGISTRY.registerSimpleBlock("c9_diorite",c_diorite_props);
	static BlockBehaviour.Properties c_andesite_props=BlockBehaviour.Properties.ofFullCopy(ANDESITE);
	public static final DeferredBlock<Block> C1_ANDESITE=REGISTRY.registerSimpleBlock("c1_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C2_ANDESITE=REGISTRY.registerSimpleBlock("c2_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C3_ANDESITE=REGISTRY.registerSimpleBlock("c3_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C4_ANDESITE=REGISTRY.registerSimpleBlock("c4_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C5_ANDESITE=REGISTRY.registerSimpleBlock("c5_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C6_ANDESITE=REGISTRY.registerSimpleBlock("c6_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C7_ANDESITE=REGISTRY.registerSimpleBlock("c7_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C8_ANDESITE=REGISTRY.registerSimpleBlock("c8_andesite",c_andesite_props);
	public static final DeferredBlock<Block> C9_ANDESITE=REGISTRY.registerSimpleBlock("c9_andesite",c_andesite_props);
	static BlockBehaviour.Properties c_granite_props=BlockBehaviour.Properties.ofFullCopy(GRANITE);
	public static final DeferredBlock<Block> C1_GRANITE=REGISTRY.registerSimpleBlock("c1_granite",c_granite_props);
	public static final DeferredBlock<Block> C2_GRANITE=REGISTRY.registerSimpleBlock("c2_granite",c_granite_props);
	public static final DeferredBlock<Block> C3_GRANITE=REGISTRY.registerSimpleBlock("c3_granite",c_granite_props);
	public static final DeferredBlock<Block> C4_GRANITE=REGISTRY.registerSimpleBlock("c4_granite",c_granite_props);
	public static final DeferredBlock<Block> C5_GRANITE=REGISTRY.registerSimpleBlock("c5_granite",c_granite_props);
	public static final DeferredBlock<Block> C6_GRANITE=REGISTRY.registerSimpleBlock("c6_granite",c_granite_props);
	public static final DeferredBlock<Block> C7_GRANITE=REGISTRY.registerSimpleBlock("c7_granite",c_granite_props);
	public static final DeferredBlock<Block> C8_GRANITE=REGISTRY.registerSimpleBlock("c8_granite",c_granite_props);
	public static final DeferredBlock<Block> C9_GRANITE=REGISTRY.registerSimpleBlock("c9_granite",c_granite_props);
	static BlockBehaviour.Properties c_tuff_props=BlockBehaviour.Properties.ofFullCopy(TUFF);
	public static final DeferredBlock<Block> C1_TUFF=REGISTRY.registerSimpleBlock("c1_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C2_TUFF=REGISTRY.registerSimpleBlock("c2_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C3_TUFF=REGISTRY.registerSimpleBlock("c3_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C4_TUFF=REGISTRY.registerSimpleBlock("c4_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C5_TUFF=REGISTRY.registerSimpleBlock("c5_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C6_TUFF=REGISTRY.registerSimpleBlock("c6_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C7_TUFF=REGISTRY.registerSimpleBlock("c7_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C8_TUFF=REGISTRY.registerSimpleBlock("c8_tuff",c_tuff_props);
	public static final DeferredBlock<Block> C9_TUFF=REGISTRY.registerSimpleBlock("c9_tuff",c_tuff_props);
	static BlockBehaviour.Properties c_stone_props=BlockBehaviour.Properties.ofFullCopy(STONE);
	public static final DeferredBlock<Block> C1_STONE=REGISTRY.registerSimpleBlock("c1_stone",c_stone_props);
	public static final DeferredBlock<Block> C2_STONE=REGISTRY.registerSimpleBlock("c2_stone",c_stone_props);
	public static final DeferredBlock<Block> C3_STONE=REGISTRY.registerSimpleBlock("c3_stone",c_stone_props);
	public static final DeferredBlock<Block> C4_STONE=REGISTRY.registerSimpleBlock("c4_stone",c_stone_props);
	public static final DeferredBlock<Block> C5_STONE=REGISTRY.registerSimpleBlock("c5_stone",c_stone_props);
	public static final DeferredBlock<Block> C6_STONE=REGISTRY.registerSimpleBlock("c6_stone",c_stone_props);
	public static final DeferredBlock<Block> C7_STONE=REGISTRY.registerSimpleBlock("c7_stone",c_stone_props);
	public static final DeferredBlock<Block> C8_STONE=REGISTRY.registerSimpleBlock("c8_stone",c_stone_props);
	public static final DeferredBlock<Block> C9_STONE=REGISTRY.registerSimpleBlock("c9_stone",c_stone_props);
	static BlockBehaviour.Properties c_netherrack_props=BlockBehaviour.Properties.ofFullCopy(NETHERRACK);
	public static final DeferredBlock<Block> C1_NETHERRACK=REGISTRY.registerSimpleBlock("c1_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C2_NETHERRACK=REGISTRY.registerSimpleBlock("c2_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C3_NETHERRACK=REGISTRY.registerSimpleBlock("c3_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C4_NETHERRACK=REGISTRY.registerSimpleBlock("c4_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C5_NETHERRACK=REGISTRY.registerSimpleBlock("c5_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C6_NETHERRACK=REGISTRY.registerSimpleBlock("c6_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C7_NETHERRACK=REGISTRY.registerSimpleBlock("c7_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C8_NETHERRACK=REGISTRY.registerSimpleBlock("c8_netherrack",c_netherrack_props);
	public static final DeferredBlock<Block> C9_NETHERRACK=REGISTRY.registerSimpleBlock("c9_netherrack",c_netherrack_props);
	static BlockBehaviour.Properties c_end_stone_props=BlockBehaviour.Properties.ofFullCopy(END_STONE);
	public static final DeferredBlock<Block> C1_END_STONE=REGISTRY.registerSimpleBlock("c1_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C2_END_STONE=REGISTRY.registerSimpleBlock("c2_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C3_END_STONE=REGISTRY.registerSimpleBlock("c3_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C4_END_STONE=REGISTRY.registerSimpleBlock("c4_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C5_END_STONE=REGISTRY.registerSimpleBlock("c5_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C6_END_STONE=REGISTRY.registerSimpleBlock("c6_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C7_END_STONE=REGISTRY.registerSimpleBlock("c7_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C8_END_STONE=REGISTRY.registerSimpleBlock("c8_end_stone",c_end_stone_props);
	public static final DeferredBlock<Block> C9_END_STONE=REGISTRY.registerSimpleBlock("c9_end_stone",c_end_stone_props);
	static BlockBehaviour.Properties c_blackstone_props=BlockBehaviour.Properties.ofFullCopy(BLACKSTONE);
	public static final DeferredBlock<Block> C1_BLACKSTONE=REGISTRY.registerSimpleBlock("c1_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C2_BLACKSTONE=REGISTRY.registerSimpleBlock("c2_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C3_BLACKSTONE=REGISTRY.registerSimpleBlock("c3_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C4_BLACKSTONE=REGISTRY.registerSimpleBlock("c4_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C5_BLACKSTONE=REGISTRY.registerSimpleBlock("c5_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C6_BLACKSTONE=REGISTRY.registerSimpleBlock("c6_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C7_BLACKSTONE=REGISTRY.registerSimpleBlock("c7_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C8_BLACKSTONE=REGISTRY.registerSimpleBlock("c8_blackstone",c_blackstone_props);
	public static final DeferredBlock<Block> C9_BLACKSTONE=REGISTRY.registerSimpleBlock("c9_blackstone",c_blackstone_props);
}
